apiVersion: v2
name: producer
description: 한투 API 데이터 핸들러와 카프카 프로듀서
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: swjh9523
    email: swjh9523@gmail.com
    url: https://github.com/seonwoojh
