{{- if .Values.producer.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-config-dev
  namespace: {{ .Values.global.namespace }}
  labels:
    app: producer-config
data:
  KAFKA_SERVER: "{{ .Values.global.kafka_broker_address }}"
  HOKA_TOPIC: "{{ .Values.global.HOKA_TOPIC }}"
  CONCLUSION_TOPIC: "{{ .Values.global.CONCLUSION_TOPIC }}"
  STOCK_CODE: "{{ .Values.producer.stockCode }}"
{{- end }}