{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deploy
  namespace: {{ .Values.global.namespace }}
  labels:
    app: producer-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
    spec:
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.global.ecrNumber }}.dkr.ecr.ap-northeast-2.amazonaws.com/stock/{{ .Chart.Name }}:latest"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1500m
              memory: 1G
          envFrom:
            - configMapRef:
                name: producer-config-dev
            - secretRef:
                name: producer-secret-dev
      imagePullSecrets:
        - name: stock-producer
{{- end }}