{{- if .Values.producer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: producer-secret-dev
  namespace: {{ .Values.global.namespace }}
  labels:
    app: producer-secret
type: Opaque
data:
  APP_KEY: {{ .Values.producer.appKey | b64enc }}
  APP_SECRET: {{ .Values.producer.appSecret | b64enc }}
{{- end }}