apiVersion: v2
name: stock_app
description: 카프카 스트림을 활용한 사용자 맞춤 주식 알림 서비스
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: producer
    version: "1.0.0"
    repository: file://charts/producer
    condition: producer.enabled

  - name: consumer
    version: "1.0.0"
    repository: file://charts/consumer
    condition: consumer.enabled

maintainers:
  - name: swjh9523
    email: swjh9523@gmail.com
    url: https://github.com/seonwoojh
