apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-config-dev
  namespace: stock

data:
  KAFKA_SERVER: ''
  HOKA_TOPIC: 'stock.samsung.hoka.data'
  CONCLUSION_TOPIC: 'stock.samsung.conclusion.data'
  STOCK_CODE: '005930'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-config-dev
  namespace: stock
data:
  INFLUX_URL: ''
  KAFKA_SERVER: ''
  GROUP_ID: 'project'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stream-config-dev
  namespace: stock

data:
  KAFKA_SERVER: ''
  SOURCE_TOPIC: 'stock.samsung.conclusion.data'
  DESTINATION_TOPIC: 'alert-topic'
  STOCK_CODE: '5930.0'