apiVersion: v2
name: consumer
description: 실시간 데이터 InfluxDB 적재 애플리케이션
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: swjh9523
    email: swjh9523@gmail.com
    url: https://github.com/seonwoojh
