{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-config-dev
  namespace: {{ .Values.global.namespace }}
data:
  KAFKA_SERVER: "{{ .Values.global.kafka_broker_address }}"
  INFLUX_URL: "{{ .Values.influxDBUrl }}"
  GROUP_ID: 'project'
{{- end }}