{{- if .Values.consumer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: consumer-secret-dev
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  INFLUX_TOKEN: "{{ .Values.consumer.influxDBToken | b64enc }}"
{{- end }}